### ISSUE TITLE
Deployment...

### ISSUE THREAD

**Issue by misolietavec** [snap22/Blog#1]
Hmm, komu je potrebný blog na localhoste? A ako je zaistená bezpečnosť (https)? Načo používatelia zadávajú email, keď nefunguje mail server?

**Comment by snap22** [comment]
Ďakujem za pripomienky, stránku som deployol na heroku, ktorý zabezpečuje https, a pridal som aj možnosť obnoviť heslo pomocou emailu, kde využívam gmail smtp server.

**Comment by misolietavec** [comment]
Dňa 17.7.2021 17:10 snap22 napísal(a):

> Ďakujem za pripomienky, stránku som deployol na heroku, ktorý 
> zabezpečuje https, a pridal som aj možnosť obnoviť heslo pomocou 
> emailu, kde využívam gmail smtp server.

Fajn. Aj semestrálka má byť v mojom ponímaní reálne použiteľná :-) 
Myslite na to pri bakalárke - môže hlavne pomôcť Vašim kolegom študentom 
(aspoň tým šikovnejším) na PaŠ-ku a všetkých ďalších predmetoch, kde sa 
jedná o spracovanie dát...

M. K.
